### PR TITLE
'solved-issue'

### PR DESCRIPTION
**Pull request by AdityaPainuli**
Hey , you can see all the major changes done by me for solving it in here . 
Most mainly , consist of installing pirsma and prisma/client which is causing the main issue for the problem .

`npm install Prisma` - for prisma installation
`npm install @prisma/client --save-dev - for prisma client installation

let me know if you still having the same issue for any other problem with it .

### CODE REVIEW

**Comment by wakywayne** [comment]
## One question

Why do we save it to dev won't we need it in production?

**Comment by AdityaPainuli** [comment]
Honestly I refer to thier docs , from what I can understand we only need prisma client in the development environment as in production it's not mandatory but I think there will be no issues with if installed in production as well . 
Also let me know if it's working for you fine

**Comment by AdityaPainuli** [comment]
https://www.reddit.com/r/node/comments/s4ll1i/can_prismaclient_be_a_development_dependency/?onetap_auto=true
This post can be more helpful in answering your question as well

**Comment by AdityaPainuli** [comment]
Hey Wakywayne/Users-Prisma-Pothos , did you check out my messages which I
posted on Upwork and GitHub.

**Pull request merged**
